//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelPriceAccessLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulePrice
    {
        public int Id { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string FulePriceDate { get; set; }
        public decimal FulePrice1 { get; set; }
    }
}
